AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Max: 350

Metrics/LineLength:
  Max: 200
  Exclude:
    - 'db/migrate/**/*'

Metrics/MethodLength:
  CountComments: false
  Max: 50

Metrics/ParameterLists:
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: false

Rails:
  Enabled: true

Style/AccessorMethodName:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/StringLiterals:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: true
